name: SSH Login Every 3 Days

# 定义触发条件：每三天触发一次
on:
  schedule:
    - cron: '0 0 */3 * *'  # 每三天的 00:00 触发
  workflow_dispatch:

jobs:
  ssh-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get current time in UTC
      id: get-time  # 设置一个ID来存储时间
      run: echo "TIME=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH into server
      id: ssh-step
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }} "
          mkdir -p ~/log && \
          echo '${{ env.TIME }} Logged in via GitHub Action.' >> ~/log/keep-action.log
        "
